// ============================================================
// BetRadar — Mock Data
// Realistic sample bets generated from plausible odds scenarios.
// Used in UI demo and when ODDS_API_KEY is not configured.
// ============================================================

import type { BetsData } from './types'

const NOW = new Date().toISOString()
const NEXT = new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString()

const mockData: BetsData = {
  generatedAt: NOW,
  nextUpdateAt: NEXT,
  activeCreditsUsed: 15,
  creditsRemaining: 485,
  lastSportsQueried: ['basketball_nba', 'baseball_mlb', 'soccer_epl', 'mma_mixed_martial_arts'],
  disclaimer:
    'BetRadar is an informational tool only. This is DEMO DATA — not live odds. ' +
    'Always verify odds with your bookmaker before placing any bets. ' +
    'Sports betting involves risk. Please gamble responsibly.',
  topValueBets: [
    {
      id: 'demo-nba-01-h2h-grizzlies',
      sport: 'NBA',
      sportKey: 'basketball_nba',
      sportTitle: 'NBA',
      league: 'NBA',
      eventId: 'demo-nba-01',
      homeTeam: 'Memphis Grizzlies',
      awayTeam: 'Golden State Warriors',
      commenceTime: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
      outcome: 'Memphis Grizzlies',
      market: 'h2h',
      marketLabel: 'Moneyline',
      bestPrice: 385,
      bestBookmaker: 'fanduel',
      bestBookmakerTitle: 'FanDuel',
      consensusImpliedProb: 0.198,
      trueOdds: 405,
      evPercent: 0.112,
      reasoning:
        'Memphis Grizzlies are priced at +385 on FanDuel, while the consensus across 8 books sets the true fair price at +405. This represents 11.2% positive expected value — the market is mispricing this outcome in your favor.',
      allOdds: [
        { bookmaker: 'fanduel', bookmakerTitle: 'FanDuel', price: 385 },
        { bookmaker: 'draftkings', bookmakerTitle: 'DraftKings', price: 360 },
        { bookmaker: 'betmgm', bookmakerTitle: 'BetMGM', price: 340 },
        { bookmaker: 'caesars', bookmakerTitle: 'Caesars', price: 355 },
        { bookmaker: 'bovada', bookmakerTitle: 'Bovada', price: 330 },
        { bookmaker: 'pointsbet', bookmakerTitle: 'PointsBet', price: 350 },
        { bookmaker: 'bet365', bookmakerTitle: 'Bet365', price: 370 },
        { bookmaker: 'williamhill', bookmakerTitle: 'William Hill', price: 345 },
      ],
    },
    {
      id: 'demo-mlb-02-h2h-athletics',
      sport: 'MLB',
      sportKey: 'baseball_mlb',
      sportTitle: 'MLB',
      league: 'MLB',
      eventId: 'demo-mlb-02',
      homeTeam: 'Oakland Athletics',
      awayTeam: 'New York Yankees',
      commenceTime: new Date(Date.now() + 9 * 3600 * 1000).toISOString(),
      outcome: 'Oakland Athletics',
      market: 'h2h',
      marketLabel: 'Moneyline',
      bestPrice: 520,
      bestBookmaker: 'bet365',
      bestBookmakerTitle: 'Bet365',
      consensusImpliedProb: 0.158,
      trueOdds: 533,
      evPercent: 0.094,
      reasoning:
        'Oakland Athletics are priced at +520 on Bet365, while the consensus across 7 books sets the true fair price at +533. This represents 9.4% positive expected value — the market is mispricing this outcome in your favor.',
      allOdds: [
        { bookmaker: 'bet365', bookmakerTitle: 'Bet365', price: 520 },
        { bookmaker: 'fanduel', bookmakerTitle: 'FanDuel', price: 480 },
        { bookmaker: 'draftkings', bookmakerTitle: 'DraftKings', price: 495 },
        { bookmaker: 'betmgm', bookmakerTitle: 'BetMGM', price: 475 },
        { bookmaker: 'bovada', bookmakerTitle: 'Bovada', price: 460 },
        { bookmaker: 'caesars', bookmakerTitle: 'Caesars', price: 490 },
        { bookmaker: 'unibet', bookmakerTitle: 'Unibet', price: 500 },
      ],
    },
    {
      id: 'demo-epl-03-h2h-brentford',
      sport: 'Soccer',
      sportKey: 'soccer_epl',
      sportTitle: 'EPL',
      league: 'English Premier League',
      eventId: 'demo-epl-03',
      homeTeam: 'Brentford',
      awayTeam: 'Arsenal',
      commenceTime: new Date(Date.now() + 18 * 3600 * 1000).toISOString(),
      outcome: 'Brentford',
      market: 'h2h',
      marketLabel: 'Moneyline',
      bestPrice: 650,
      bestBookmaker: 'williamhill',
      bestBookmakerTitle: 'William Hill',
      consensusImpliedProb: 0.128,
      trueOdds: 681,
      evPercent: 0.183,
      reasoning:
        'Brentford are priced at +650 on William Hill, while the consensus across 9 books sets the true fair price at +681. This represents 18.3% positive expected value — the market is significantly mispricing this outcome in your favor.',
      allOdds: [
        { bookmaker: 'williamhill', bookmakerTitle: 'William Hill', price: 650 },
        { bookmaker: 'bet365', bookmakerTitle: 'Bet365', price: 620 },
        { bookmaker: 'betfair', bookmakerTitle: 'Betfair', price: 610 },
        { bookmaker: 'ladbrokes', bookmakerTitle: 'Ladbrokes', price: 600 },
        { bookmaker: 'unibet', bookmakerTitle: 'Unibet', price: 595 },
        { bookmaker: 'fanduel', bookmakerTitle: 'FanDuel', price: 580 },
        { bookmaker: 'draftkings', bookmakerTitle: 'DraftKings', price: 590 },
        { bookmaker: 'betmgm', bookmakerTitle: 'BetMGM', price: 575 },
        { bookmaker: 'pinnacle', bookmakerTitle: 'Pinnacle', price: 605 },
      ],
    },
    {
      id: 'demo-mma-04-h2h-fighter',
      sport: 'MMA',
      sportKey: 'mma_mixed_martial_arts',
      sportTitle: 'MMA',
      league: 'UFC',
      eventId: 'demo-mma-04',
      homeTeam: 'Paddy Pimblett',
      awayTeam: 'Dustin Poirier',
      commenceTime: new Date(Date.now() + 30 * 3600 * 1000).toISOString(),
      outcome: 'Paddy Pimblett',
      market: 'h2h',
      marketLabel: 'Moneyline',
      bestPrice: 380,
      bestBookmaker: 'draftkings',
      bestBookmakerTitle: 'DraftKings',
      consensusImpliedProb: 0.204,
      trueOdds: 390,
      evPercent: 0.076,
      reasoning:
        'Paddy Pimblett is priced at +380 on DraftKings, while the consensus across 6 books sets the true fair price at +390. This represents 7.6% positive expected value — the market is mispricing this outcome in your favor.',
      allOdds: [
        { bookmaker: 'draftkings', bookmakerTitle: 'DraftKings', price: 380 },
        { bookmaker: 'fanduel', bookmakerTitle: 'FanDuel', price: 360 },
        { bookmaker: 'betmgm', bookmakerTitle: 'BetMGM', price: 350 },
        { bookmaker: 'caesars', bookmakerTitle: 'Caesars', price: 355 },
        { bookmaker: 'bovada', bookmakerTitle: 'Bovada', price: 340 },
        { bookmaker: 'unibet', bookmakerTitle: 'Unibet', price: 365 },
      ],
    },
    {
      id: 'demo-nba-05-h2h-hornets',
      sport: 'NBA',
      sportKey: 'basketball_nba',
      sportTitle: 'NBA',
      league: 'NBA',
      eventId: 'demo-nba-05',
      homeTeam: 'Charlotte Hornets',
      awayTeam: 'Boston Celtics',
      commenceTime: new Date(Date.now() + 8 * 3600 * 1000).toISOString(),
      outcome: 'Charlotte Hornets',
      market: 'h2h',
      marketLabel: 'Moneyline',
      bestPrice: 460,
      bestBookmaker: 'betmgm',
      bestBookmakerTitle: 'BetMGM',
      consensusImpliedProb: 0.174,
      trueOdds: 475,
      evPercent: 0.066,
      reasoning:
        'Charlotte Hornets are priced at +460 on BetMGM, while the consensus across 7 books sets the true fair price at +475. This represents 6.6% positive expected value — the market is mispricing this outcome in your favor.',
      allOdds: [
        { bookmaker: 'betmgm', bookmakerTitle: 'BetMGM', price: 460 },
        { bookmaker: 'fanduel', bookmakerTitle: 'FanDuel', price: 440 },
        { bookmaker: 'draftkings', bookmakerTitle: 'DraftKings', price: 435 },
        { bookmaker: 'caesars', bookmakerTitle: 'Caesars', price: 430 },
        { bookmaker: 'bet365', bookmakerTitle: 'Bet365', price: 445 },
        { bookmaker: 'pointsbet', bookmakerTitle: 'PointsBet', price: 420 },
        { bookmaker: 'unibet', bookmakerTitle: 'Unibet', price: 425 },
      ],
    },
    {
      id: 'demo-mlb-06-h2h-rockies',
      sport: 'MLB',
      sportKey: 'baseball_mlb',
      sportTitle: 'MLB',
      league: 'MLB',
      eventId: 'demo-mlb-06',
      homeTeam: 'Colorado Rockies',
      awayTeam: 'Los Angeles Dodgers',
      commenceTime: new Date(Date.now() + 11 * 3600 * 1000).toISOString(),
      outcome: 'Colorado Rockies',
      market: 'h2h',
      marketLabel: 'Moneyline',
      bestPrice: 760,
      bestBookmaker: 'caesars',
      bestBookmakerTitle: 'Caesars',
      consensusImpliedProb: 0.111,
      trueOdds: 800,
      evPercent: 0.149,
      reasoning:
        'Colorado Rockies are priced at +760 on Caesars, while the consensus across 6 books sets the true fair price at +800. This represents 14.9% positive expected value — the market is significantly mispricing this outcome in your favor.',
      allOdds: [
        { bookmaker: 'caesars', bookmakerTitle: 'Caesars', price: 760 },
        { bookmaker: 'fanduel', bookmakerTitle: 'FanDuel', price: 700 },
        { bookmaker: 'draftkings', bookmakerTitle: 'DraftKings', price: 720 },
        { bookmaker: 'betmgm', bookmakerTitle: 'BetMGM', price: 710 },
        { bookmaker: 'bet365', bookmakerTitle: 'Bet365', price: 740 },
        { bookmaker: 'bovada', bookmakerTitle: 'Bovada', price: 690 },
      ],
    },
  ],
  parlays: [
    {
      id: 'parlay-3leg-demo-a',
      legs: [
        {
          bet: {
            id: 'demo-epl-03-h2h-brentford',
            sport: 'EPL',
            sportKey: 'soccer_epl',
            sportTitle: 'EPL',
            league: 'English Premier League',
            eventId: 'demo-epl-03',
            homeTeam: 'Brentford',
            awayTeam: 'Arsenal',
            commenceTime: new Date(Date.now() + 18 * 3600 * 1000).toISOString(),
            outcome: 'Brentford',
            market: 'h2h',
            marketLabel: 'Moneyline',
            bestPrice: 650,
            bestBookmaker: 'williamhill',
            bestBookmakerTitle: 'William Hill',
            consensusImpliedProb: 0.128,
            trueOdds: 681,
            evPercent: 0.183,
            reasoning: '',
            allOdds: [],
          },
          price: 650,
        },
        {
          bet: {
            id: 'demo-nba-01-h2h-grizzlies',
            sport: 'NBA',
            sportKey: 'basketball_nba',
            sportTitle: 'NBA',
            league: 'NBA',
            eventId: 'demo-nba-01',
            homeTeam: 'Memphis Grizzlies',
            awayTeam: 'Golden State Warriors',
            commenceTime: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
            outcome: 'Memphis Grizzlies',
            market: 'h2h',
            marketLabel: 'Moneyline',
            bestPrice: 385,
            bestBookmaker: 'fanduel',
            bestBookmakerTitle: 'FanDuel',
            consensusImpliedProb: 0.198,
            trueOdds: 405,
            evPercent: 0.112,
            reasoning: '',
            allOdds: [],
          },
          price: 385,
        },
        {
          bet: {
            id: 'demo-mlb-06-h2h-rockies',
            sport: 'MLB',
            sportKey: 'baseball_mlb',
            sportTitle: 'MLB',
            league: 'MLB',
            eventId: 'demo-mlb-06',
            homeTeam: 'Colorado Rockies',
            awayTeam: 'Los Angeles Dodgers',
            commenceTime: new Date(Date.now() + 11 * 3600 * 1000).toISOString(),
            outcome: 'Colorado Rockies',
            market: 'h2h',
            marketLabel: 'Moneyline',
            bestPrice: 760,
            bestBookmaker: 'caesars',
            bestBookmakerTitle: 'Caesars',
            consensusImpliedProb: 0.111,
            trueOdds: 800,
            evPercent: 0.149,
            reasoning: '',
            allOdds: [],
          },
          price: 760,
        },
      ],
      combinedAmericanOdds: 38900,
      combinedDecimalOdds: 390,
      impliedProbability: 0.00256,
      estimatedEvPercent: 0.264,
      sports: ['soccer_epl', 'basketball_nba', 'baseball_mlb'],
      reasoning:
        '3-leg parlay paying +38900. Each leg independently identified as +EV vs. the market consensus. Leg 1: Brentford (EPL, +650) | Leg 2: Memphis Grizzlies (NBA, +385) | Leg 3: Colorado Rockies (MLB, +760). All legs span different sports/events for maximum independence.',
      tier: 'elite',
    },
    {
      id: 'parlay-4leg-demo-b',
      legs: [
        {
          bet: {
            id: 'demo-epl-03-h2h-brentford',
            sport: 'EPL',
            sportKey: 'soccer_epl',
            sportTitle: 'EPL',
            league: 'English Premier League',
            eventId: 'demo-epl-03',
            homeTeam: 'Brentford',
            awayTeam: 'Arsenal',
            commenceTime: new Date(Date.now() + 18 * 3600 * 1000).toISOString(),
            outcome: 'Brentford',
            market: 'h2h',
            marketLabel: 'Moneyline',
            bestPrice: 650,
            bestBookmaker: 'williamhill',
            bestBookmakerTitle: 'William Hill',
            consensusImpliedProb: 0.128,
            trueOdds: 681,
            evPercent: 0.183,
            reasoning: '',
            allOdds: [],
          },
          price: 650,
        },
        {
          bet: {
            id: 'demo-nba-01-h2h-grizzlies',
            sport: 'NBA',
            sportKey: 'basketball_nba',
            sportTitle: 'NBA',
            league: 'NBA',
            eventId: 'demo-nba-01',
            homeTeam: 'Memphis Grizzlies',
            awayTeam: 'Golden State Warriors',
            commenceTime: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
            outcome: 'Memphis Grizzlies',
            market: 'h2h',
            marketLabel: 'Moneyline',
            bestPrice: 385,
            bestBookmaker: 'fanduel',
            bestBookmakerTitle: 'FanDuel',
            consensusImpliedProb: 0.198,
            trueOdds: 405,
            evPercent: 0.112,
            reasoning: '',
            allOdds: [],
          },
          price: 385,
        },
        {
          bet: {
            id: 'demo-mlb-02-h2h-athletics',
            sport: 'MLB',
            sportKey: 'baseball_mlb',
            sportTitle: 'MLB',
            league: 'MLB',
            eventId: 'demo-mlb-02',
            homeTeam: 'Oakland Athletics',
            awayTeam: 'New York Yankees',
            commenceTime: new Date(Date.now() + 9 * 3600 * 1000).toISOString(),
            outcome: 'Oakland Athletics',
            market: 'h2h',
            marketLabel: 'Moneyline',
            bestPrice: 520,
            bestBookmaker: 'bet365',
            bestBookmakerTitle: 'Bet365',
            consensusImpliedProb: 0.158,
            trueOdds: 533,
            evPercent: 0.094,
            reasoning: '',
            allOdds: [],
          },
          price: 520,
        },
        {
          bet: {
            id: 'demo-mma-04-h2h-fighter',
            sport: 'MMA',
            sportKey: 'mma_mixed_martial_arts',
            sportTitle: 'MMA',
            league: 'UFC',
            eventId: 'demo-mma-04',
            homeTeam: 'Paddy Pimblett',
            awayTeam: 'Dustin Poirier',
            commenceTime: new Date(Date.now() + 30 * 3600 * 1000).toISOString(),
            outcome: 'Paddy Pimblett',
            market: 'h2h',
            marketLabel: 'Moneyline',
            bestPrice: 380,
            bestBookmaker: 'draftkings',
            bestBookmakerTitle: 'DraftKings',
            consensusImpliedProb: 0.204,
            trueOdds: 390,
            evPercent: 0.076,
            reasoning: '',
            allOdds: [],
          },
          price: 380,
        },
      ],
      combinedAmericanOdds: 216000,
      combinedDecimalOdds: 2161,
      impliedProbability: 0.000463,
      estimatedEvPercent: 0.229,
      sports: ['soccer_epl', 'basketball_nba', 'baseball_mlb', 'mma_mixed_martial_arts'],
      reasoning:
        '4-leg parlay paying +216000. Each leg independently identified as +EV vs. the market consensus. Leg 1: Brentford (EPL, +650) | Leg 2: Memphis Grizzlies (NBA, +385) | Leg 3: Oakland Athletics (MLB, +520) | Leg 4: Paddy Pimblett (MMA, +380). All legs span different sports/events for maximum independence.',
      tier: 'elite',
    },
  ],
}

export default mockData
